version: '3.8'

services:
  fake-news-api:
    build: .
    container_name: fake-news-detection-api
    ports:
      - "9999:9999"
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - GEMINI_MODEL=${GEMINI_MODEL:-gemini-2.5-flash}
      - AGENT_SYSTEM=${AGENT_SYSTEM:-}
      - AGENT_STYLE=${AGENT_STYLE:-}
    volumes:
      - ./.env:/app/.env:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9999/docs"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - fake-news-network

  fake-news-frontend:
    build: ./frontend
    container_name: fake-news-detection-frontend
    ports:
      - "3000:3000"
    depends_on:
      - fake-news-api
    restart: unless-stopped
    networks:
      - fake-news-network

networks:
  fake-news-network:
    driver: bridge 